# Generated by Django 3.2 on 2021-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField(max_length=700)),
                ('subject', models.TextField(max_length=700)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
